services:
  vfs-bot:
    build: .
    container_name: vfs-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATA_DIR=/app/data
      - PWDEBUG=0
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

